-- espresso_shots: monthly range partitioning.
-- Generated by scripts/generate-partition-migration.mjs. Do not hand-edit.

DROP TABLE IF EXISTS espresso_shots CASCADE;

CREATE TABLE espresso_shots (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "org_id" uuid NOT NULL,
  "site_id" uuid NOT NULL,
  "machine_id" uuid NOT NULL,
  "group_number" integer NOT NULL DEFAULT 1,
  "external_id" text NOT NULL,
  "pulled_at" timestamp with time zone NOT NULL,
  "dose_g" numeric(8, 2),
  "yield_g" numeric(8, 2),
  "duration_s" numeric(8, 2),
  "brew_temp_c" numeric(6, 2),
  "peak_pressure_bar" numeric(5, 2),
  "grind_setting" text,
  "verdict" shot_verdict NOT NULL DEFAULT 'in_spec',
  "ratio" numeric(6, 3),
  "roasted_lot_id" uuid,
  "blend_id" uuid,
  "product_id" uuid,
  "barista_ref" text,
  "profile" bytea,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY ("id", "pulled_at")
) PARTITION BY RANGE (pulled_at);

ALTER TABLE espresso_shots
  ADD CONSTRAINT espresso_shots_org_id_organizations_id_fk FOREIGN KEY ("org_id")
    REFERENCES organizations("id") ON DELETE CASCADE;

CREATE UNIQUE INDEX espresso_shots_dedupe_idx ON espresso_shots ("org_id", "machine_id", "external_id", "pulled_at");
CREATE INDEX espresso_shots_site_pulled_idx ON espresso_shots ("org_id", "site_id", "pulled_at");
CREATE INDEX espresso_shots_machine_pulled_idx ON espresso_shots ("org_id", "machine_id", "pulled_at");
CREATE INDEX espresso_shots_verdict_idx ON espresso_shots ("org_id", "verdict", "pulled_at");

CREATE TABLE IF NOT EXISTS espresso_shots_2026_08 PARTITION OF espresso_shots FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE IF NOT EXISTS espresso_shots_2026_09 PARTITION OF espresso_shots FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE IF NOT EXISTS espresso_shots_2026_10 PARTITION OF espresso_shots FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE IF NOT EXISTS espresso_shots_2026_11 PARTITION OF espresso_shots FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE IF NOT EXISTS espresso_shots_2026_12 PARTITION OF espresso_shots FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');

-- A shot that arrives outside every range would otherwise be REJECTED, and a
-- bar bridge with a wrong clock is not a reason to lose data. The cron keeps
-- the rolling window ahead; this catches everything else.
CREATE TABLE IF NOT EXISTS espresso_shots_overflow PARTITION OF espresso_shots DEFAULT;
