/**
 * The one way schema reaches a database.
 *
 * Three things happen here that `drizzle-kit migrate` alone does not do, each
 * of which has a specific failure behind it.
 *
 * ADVISORY LOCK. Two deploys racing — a re-run of a failed job, a push landing
 * while the previous one is still deploying — both run migrate against the
 * same database. drizzle-kit takes no lock, so both read the same journal and
 * both apply the same file. Whichever loses gets a duplicate-object error
 * halfway through a migration that is not transactional as a whole, leaving
 * the schema between two states. A session-level advisory lock serialises them
 * instead: the second waits, then finds nothing to do.
 *
 * BRANCH GUARD. The staging deploy script migrated whatever DATABASE_URL
 * happened to be exported in the operator's shell, with a comment asking them
 * to check. `--target` makes the intended environment explicit and compares it
 * with the host actually being connected to, so pointing at the wrong Neon
 * branch fails before any DDL rather than after.
 *
 * SEED BUILT FIRST. The authz vocabulary is generated by importing a TypeScript
 * module, which needs Node's type stripping. Built after drizzle-kit ran, a
 * Node version without it failed at the point where the schema was already
 * applied and the vocabulary was not — every permission check denying, for
 * everyone, including owners. Building it first turns that into a clean refusal
 * that changes nothing.
 *
 *   node scripts/migrate.mjs --target local|staging|production
 */
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { config } from "dotenv";
import pg from "pg";

config({ path: "../../.env", quiet: true });
config({ path: "../../../.env", quiet: true });

const args = process.argv.slice(2);
const targetArg = args.indexOf("--target");
const target = targetArg === -1 ? "local" : args[targetArg + 1];

const ENVIRONMENTS = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "environments.json"), "utf8"),
);

if (!ENVIRONMENTS[target] || target === "//") {
  console.error(
    `unknown --target ${target}; expected one of ${Object.keys(ENVIRONMENTS)
      .filter((k) => k !== "//")
      .join(", ")}`,
  );
  process.exit(1);
}

const url = process.env.DATABASE_URL;
if (!url) {
  console.error("DATABASE_URL is not set");
  process.exit(1);
}

/**
 * The host must match the target.
 *
 * Neon branch endpoints are per-branch hostnames, so the host is what
 * distinguishes production from staging. Endpoint hostnames are not secrets —
 * they are useless without the credential — so they are committed rather than
 * held in a variable that could itself be wrong.
 */
const host = new URL(url).hostname;
const expected = ENVIRONMENTS[target].hosts;
if (!expected.some((h) => host === h || host.endsWith(`.${h}`))) {
  console.error(
    `refusing to migrate: --target ${target} expects ${expected.join(" or ")}, ` +
      `but DATABASE_URL points at ${host}.\n` +
      "  Check which Neon branch is exported before re-running.",
  );
  process.exit(1);
}

// Built BEFORE any DDL: see the header.
const { buildAuthzSql, AUTHZ_COUNTS } = await import("./generate-authz-migration.mjs");
const authzSql = buildAuthzSql();

const LOCK_KEY = "roastery:migrate";

const client = new pg.Client({ connectionString: url });
await client.connect();
try {
  console.log(`==> ${target} (${host})`);
  await client.query("SELECT pg_advisory_lock(hashtext($1))", [LOCK_KEY]);

  // pg_trgm backs the trigram indexes 0000_init.sql creates, so it has to
  // exist before drizzle-kit runs rather than alongside it.
  await client.query("CREATE EXTENSION IF NOT EXISTS pg_trgm");
  console.log("    extensions ok (pg_trgm)");

  const drizzle = spawnSync("pnpm", ["exec", "drizzle-kit", "migrate"], {
    stdio: "inherit",
    cwd: join(import.meta.dirname, ".."),
  });
  if (drizzle.status !== 0) {
    throw new Error(`drizzle-kit migrate exited ${drizzle.status}`);
  }

  // One transaction: a half-applied vocabulary is a role holding grants to
  // permissions that do not exist yet.
  await client.query("BEGIN");
  await client.query(authzSql);
  await client.query("COMMIT");
  const { permissions, roles, plans } = AUTHZ_COUNTS;
  console.log(`    authz seeded (${permissions} permissions, ${roles} roles, ${plans} plans)`);
} catch (error) {
  await client.query("ROLLBACK").catch(() => {});
  throw error;
} finally {
  // Released explicitly rather than left to the session ending, so a pooled or
  // slow-to-close connection cannot hold the next deploy.
  await client.query("SELECT pg_advisory_unlock(hashtext($1))", [LOCK_KEY]).catch(() => {});
  await client.end();
}
